#
# This is the config file where you put the title
# These have to be in the following format:
# prefixes:
#   <name>:
#     chattag: <chattag>
#     headtag: <headtag>
#     permission: <permission needed>
#     description: <description>
# suffixes:
#   <name>:
#     chattag: <chattag>
#     headtag: <headtag>
#     permission: <permission needed>
#     description: <description>
# default_prefix: <name>
# default_suffix: <name>
#
# Chattag, headtag, permission and description are optional, although it is usefull
# if at least one of chattag and headtag is set ;-)
#
#
#
prefixes:
  Noob:
    chattag: &aNoob
    headtag: &aNoob
    permission: title.noob.prefix
    description: '&6&oA &d&ospecial &6&oTitle for &d&oSpecial &6&oPeople'
suffixes:
  Noob:
    chattag: &aNoob
    headtag: &aNoob
    permission: title.noob.suffix
    description: '&6&oA &d&ospecial &6&oTitle for &d&oSpecial &6&oPeople'
default_prefix: 'Noob'
default_suffix: 'Noob'